website_url: "http://172.17.166.115"
api_key: "b82b104597eb26d1f1b40a80e13eff61ef861b7f462afcfa8de775c6e283f931"
api_username: "system"

require_min_length: 50
require_max_length: 32000





workflow:
  - dir: 
      - "MtF-wiki/content/zh-cn"
    recursive: true
    mode_str:
      - "*.md"
    tags:
      - "MtF-Wiki"
    category_num: 31